development: &default
  adapter: postgresql
  database: tourganizer_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: tourganizer_test
  min_messages: warning
